baseURL = 'https://nikolaushuber.github.io/'
languageCode = 'en-us'
title = 'Nikolaus Huber'
theme = "clarity"

DefaultContentLanguage = "en" 

[taxonomies]
category = "categories"
tag = "tags" 
series = "series" 
