author = "Nikolaus Huber" 
showShare = false 
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "PhD Student @ Uppsala University"
mainSections = ['blog']
usePageBundles = true 
footerLogo = "" 
iconsDir = "icons/"
enforceLightMode = true 
since=2021
ga_verify="kBsOLlBBOlacxyFURHNS5scWNbD8XcWgfgj2VcXA-5g"
